[package]
name = "august-core"
version = "0.1.0"
edition = "2024"

[dependencies]
august-plugin-system = { git = "https://github.com/BleynChannel/august-plugin-system.git", branch = "master" }
sled = "0.34.7"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
async-trait = "0.1.89"
log = "0.4.27"